[naverpost_cine21_review]
title = "씨네21 ─ 20자평"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=520134&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_news]
title = "씨네21 ─ 국내뉴스"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=450865&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_view]
title = "씨네21 ─ 알고봅시다"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=269621&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_feature]
title = "씨네21 ─ feature"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=229028&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_whoareyou]
title = "씨네21 ─ Who are you"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=371914&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_foreignnews]
title = "씨네21 ─ 해외뉴스"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=452114&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_coverstar]
title = "씨네21 ─ 커버스타"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=228138&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_interview]
title = "씨네21 ─ 인터뷰"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=229029&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
